### ISSUE TITLE
Does this work with modern version of revit?

### ISSUE THREAD

**Issue by guysoft** [acnicholas/FileUpgrader#1]
Using 2021 here, thanks

**Comment by acnicholas** [comment]
Hi @guysoft,

Yes, it seems to work OK.
To get the current release to work with Revit 2021, you can do the following:

```
copy both these files
C:\ProgramData\Autodesk\Revit\Addins\2017\ADNPlugin-FileUpgrader.addin
C:\ProgramData\Autodesk\Revit\Addins\2017\ADNPlugin-FileUpgrader.dll

to

C:\ProgramData\Autodesk\Revit\Addins\2021\
```


I will create a new release shortly for Revit versions 2018 and up.

**Comment by guysoft** [comment]
Hey, I assume this only works after you make the new release?

Also you might want to take a look at this, you can get github to automatically build revit addons and release them:
https://github.com/SOM-Firmwide/build-revit-addin-action

**Comment by acnicholas** [comment]
It seemed to work without making a new release, but it was probably time for a proper update.

So, I have created a new installer which now supports Revit versions 2017-2021.
 [V21.0.0](https://github.com/acnicholas/FileUpgrader/releases/tag/v21.0.0)

Only tested with Revit 2019-2021 (but I guess 2018 works).

Thanks for the link. I will check it out.
