### ISSUE TITLE
Missing "cab1.cab" when installing

### ISSUE THREAD

**Issue by vinnividivicci** [acnicholas/FileUpgrader#2]
Hello,

When I try to install this add-in using the MSI, I get this error:
![image](https://user-images.githubusercontent.com/591242/146786571-bff4369b-c094-4052-b5e5-a96874afec3a.png)

And then the installation must be cancelled

**Comment by acnicholas** [comment]
Hi @vinnividivicci ,

I've create a new release [[v22.0.0](https://github.com/acnicholas/FileUpgrader/releases/tag/v22.0.0)] with an updated installer and Revit 2022 support.
...This should[hopefully] be working now.

Cheers
