### ISSUE TITLE
Missing DLL

### ISSUE THREAD

**Issue by Krzystoffer** [acnicholas/FileUpgrader#4]
The ReadMe step 2 asks to “Copy the plugin module "ADNPlugin-FileUpgrader.dll" to a location on your local system”, 
but that DLL isn’t provided – where can I download this from ?

**Comment by acnicholas** [comment]
Hi @Krzystoffer,

I have actually packaged up the DLL in a windows installer.
You can get the current release here [https://github.com/acnicholas/FileUpgrader/releases/tag/v22.0.0](https://github.com/acnicholas/FileUpgrader/releases/tag/v22.0.0)

Apologies, those notes were just copied verbatim from the original release (by the Autodesk Developer Network).
I probably should fix/remove the installation notes.

**Comment by Krzystoffer** [comment]
Thanks Nicholas
That worked a treat!
